// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdrOJpeKqSoWDdhLpZRsqBdbcCPwKx8y4',
    appId: '1:105077450467:web:95ca46126b0475f8e507d6',
    messagingSenderId: '105077450467',
    projectId: 'belajar-firebase-satu-4b932',
    authDomain: 'belajar-firebase-satu-4b932.firebaseapp.com',
    storageBucket: 'belajar-firebase-satu-4b932.appspot.com',
    measurementId: 'G-KMV5RFQPTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjeIhrVI9U5haTaEai5A6vtoXeIjxw-pU',
    appId: '1:105077450467:android:4f0220388a1fec33e507d6',
    messagingSenderId: '105077450467',
    projectId: 'belajar-firebase-satu-4b932',
    storageBucket: 'belajar-firebase-satu-4b932.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7kGCwY3ZkpFP-5wY_jrwBIRPRd-G47j8',
    appId: '1:105077450467:ios:b2d38d51a167d89fe507d6',
    messagingSenderId: '105077450467',
    projectId: 'belajar-firebase-satu-4b932',
    storageBucket: 'belajar-firebase-satu-4b932.appspot.com',
    iosClientId: '105077450467-di563dfq9io0c4vt14ak27qekcr9j39q.apps.googleusercontent.com',
    iosBundleId: 'com.example.belajarFirebaseSatu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7kGCwY3ZkpFP-5wY_jrwBIRPRd-G47j8',
    appId: '1:105077450467:ios:b2d38d51a167d89fe507d6',
    messagingSenderId: '105077450467',
    projectId: 'belajar-firebase-satu-4b932',
    storageBucket: 'belajar-firebase-satu-4b932.appspot.com',
    iosClientId: '105077450467-di563dfq9io0c4vt14ak27qekcr9j39q.apps.googleusercontent.com',
    iosBundleId: 'com.example.belajarFirebaseSatu',
  );
}
